// <auto-generated />
using BlazorBooks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorBooks.Migrations
{
    [DbContext(typeof(BlazorBooksContext))]
    partial class BlazorBooksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorBooks.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Dustin Boswell, Trevor Foucher",
                            PublishedYear = 2012,
                            Publisher = "オライリージャパン",
                            Title = "リーダブルコード"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.K.ローリング",
                            PublishedYear = 1999,
                            Publisher = "静山社",
                            Title = "ハリー・ポッターと賢者の石"
                        },
                        new
                        {
                            Id = 3,
                            Author = "司馬遼太郎",
                            PublishedYear = 1999,
                            Publisher = "文藝春秋",
                            Title = "坂の上の雲"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
